In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 2.84955262,  1.10921914,  2.77543034, ...,  1.52716263,
        -0.48996249, -0.33210575],
       [-0.77426138, -1.94432189, -0.76659246, ..., -0.33637833,
         0.23227137,  0.11103649],
       [-0.64548121, -0.10084582, -0.67258329, ..., -0.65576664,
        -0.5889922 , -0.18815508],
       ...,
       [ 1.97804033,  2.25798625,  2.12559739, ...,  2.403333  ,
         2.06090605,  2.29965106],
       [ 1.66357713,  0.86856833,  1.64038879, ...,  1.11484716,
        -0.51898844, -0.40887943],
       [-0.15431965,  0.32596884, -0.11416018, ...,  1.791107  ,
        -0.12457704,  1.34562511]])

In [9]:
y_train

339    M
120    B
211    B
208    B
464    B
      ..
17     M
556    B
567    M
389    M
39     M
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])

Numpy arrays to pytorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [44]:
import torch.nn as nn

# Defining the model
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
     super().__init__()
     self.linear = nn.Linear(num_features,1)
     self.sigmoid = nn.Sigmoid()
     # Initialize the criterion once
     self.criterion = nn.BCELoss()
     self.optimizer = torch.optim.SGD(self.parameters(), lr=0.1)

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self,y_pred,y_true):
    loss = self.criterion(y_pred, y_true)
    return loss

In [36]:
# Important parameters
learning_rate = 0.1
epochs = 25

In [48]:
# Training Pipeline
model = MySimpleNN(X_train_tensor.shape[1])
# define loop epochs time
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor.float())
  # loss calculate
  loss = model.loss_function(y_pred,y_train_tensor.view(-1,1).float())
  # print(loss)
  # zero gradients
  model.optimizer.zero_grad()
  # backward pass
  loss.backward()
  # parameters update
  model.optimizer.step()
  # print loss in each epoch
  print(f'Epoch:{epoch + 1}, Loss: {loss.item()}')

Epoch:1, Loss: 0.46115824580192566
Epoch:2, Loss: 0.40678897500038147
Epoch:3, Loss: 0.36791011691093445
Epoch:4, Loss: 0.3384239673614502
Epoch:5, Loss: 0.3151244521141052
Epoch:6, Loss: 0.2961452901363373
Epoch:7, Loss: 0.28031864762306213
Epoch:8, Loss: 0.26687243580818176
Epoch:9, Loss: 0.2552737295627594
Epoch:10, Loss: 0.24514172971248627
Epoch:11, Loss: 0.23619619011878967
Epoch:12, Loss: 0.228225976228714
Epoch:13, Loss: 0.2210686355829239
Epoch:14, Loss: 0.2145969569683075
Epoch:15, Loss: 0.2087097465991974
Epoch:16, Loss: 0.20332540571689606
Epoch:17, Loss: 0.1983773559331894
Epoch:18, Loss: 0.1938105672597885
Epoch:19, Loss: 0.18957921862602234
Epoch:20, Loss: 0.18564483523368835
Epoch:21, Loss: 0.18197472393512726
Epoch:22, Loss: 0.17854103446006775
Epoch:23, Loss: 0.17531976103782654
Epoch:24, Loss: 0.17229020595550537
Epoch:25, Loss: 0.16943427920341492

In [49]:
model.linear.weight

Parameter containing:
tensor([[ 0.1531,  0.2086,  0.1159,  0.3565,  0.0225,  0.2497,  0.2713,  0.1949,
          0.1335, -0.0604,  0.2396, -0.0422,  0.3057,  0.0245,  0.1194, -0.0444,
         -0.0052, -0.1270, -0.1587,  0.0221,  0.3802,  0.1589,  0.2736,  0.3598,
          0.2070,  0.2830, -0.0160,  0.3057,  0.2692,  0.0067]],
       requires_grad=True)

In [50]:
model.linear.bias

Parameter containing:
tensor([-0.1106], requires_grad=True)

In [51]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy.item()}')

Accuracy:0.5030778646469116