In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.82302858, -1.05504297, -0.85529869, ..., -1.47920827,
        -0.17011484, -0.5255259 ],
       [-0.74062318, -2.00018212, -0.75826334, ..., -1.01721626,
         0.71438563, -0.51699266],
       [-0.55023828, -1.21567007, -0.54974056, ..., -0.34650936,
        -0.38239495,  0.22433288],
       ...,
       [ 0.14026218, -0.94795824,  0.1518044 , ...,  0.38558427,
         0.34674109,  0.03713485],
       [-0.1183203 ,  0.76772538,  0.06220154, ...,  1.61483466,
         1.03126754,  3.15016877],
       [ 1.60651006,  0.52329284,  1.55282974, ...,  1.0267346 ,
         0.22214189, -0.0791306 ]])

In [11]:
y_train

333    B
313    B
386    B
492    M
36     M
      ..
69     B
389    M
89     B
14     M
218    M
Name: diagnosis, Length: 455, dtype: object

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

Numpy arrays to pytorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

In [17]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [26]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)
print(train_dataset[10])
print("\n=====================")

(tensor([ 0.5324,  0.9144,  0.4380,  0.4071, -1.0283, -0.7190, -0.7021, -0.4103,
        -1.0349, -0.8107, -0.1043, -0.0733, -0.2053,  0.0031, -0.9715, -0.9055,
        -0.6727, -0.6840, -0.7284, -0.2873,  0.5945,  1.3101,  0.4874,  0.4720,
        -0.6256, -0.6259, -0.5973, -0.2199,  0.0345,  0.0259],
       dtype=torch.float64), tensor(1))

=====================

In [27]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [19]:
import torch.nn as nn

# Defining the model
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
     super().__init__()
     self.linear = nn.Linear(num_features,1)
     self.sigmoid = nn.Sigmoid()
     # Initialize the criterion once
     self.criterion = nn.BCELoss()
     self.optimizer = torch.optim.SGD(self.parameters(), lr=0.1)

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self,y_pred,y_true):
    loss = self.criterion(y_pred, y_true)
    return loss

In [20]:
# Important parameters
learning_rate = 0.1
epochs = 25

In [28]:
# Training Pipeline
model = MySimpleNN(X_train_tensor.shape[1])
# define loop epochs time
for epoch in range(epochs):

  for batch_features,batch_labels in train_loader:
    # forward pass
    y_pred = model(batch_features.float())
    # loss calculate
    loss = model.loss_function(y_pred,batch_labels.view(-1,1).float())
    # print(loss)
    # zero gradients
    model.optimizer.zero_grad()
    # backward pass
    loss.backward()
    # parameters update
    model.optimizer.step()
  # print loss in each epoch
  print(f'Epoch:{epoch + 1}, Loss: {loss.item()}')

Epoch:1, Loss: 0.41130882501602173
Epoch:2, Loss: 0.11826150864362717
Epoch:3, Loss: 0.09451664239168167
Epoch:4, Loss: 0.1877102106809616
Epoch:5, Loss: 0.03627755492925644
Epoch:6, Loss: 0.28094857931137085
Epoch:7, Loss: 0.2829044461250305
Epoch:8, Loss: 0.03629707545042038
Epoch:9, Loss: 0.053880419582128525
Epoch:10, Loss: 0.08895669132471085
Epoch:11, Loss: 0.08580117672681808
Epoch:12, Loss: 0.18344278633594513
Epoch:13, Loss: 0.2642609179019928
Epoch:14, Loss: 0.16144287586212158
Epoch:15, Loss: 0.19421494007110596
Epoch:16, Loss: 0.20184287428855896
Epoch:17, Loss: 0.14554813504219055
Epoch:18, Loss: 0.1005067303776741
Epoch:19, Loss: 0.04085608944296837
Epoch:20, Loss: 0.13652731478214264
Epoch:21, Loss: 0.024307815358042717
Epoch:22, Loss: 0.029018601402640343
Epoch:23, Loss: 0.06966044008731842
Epoch:24, Loss: 0.00708394730463624
Epoch:25, Loss: 0.29558849334716797

In [22]:
model.linear.weight

Parameter containing:
tensor([[ 0.1394,  0.2004,  0.2078,  0.2482,  0.2678,  0.0633,  0.1475,  0.1921,
          0.1362, -0.1128,  0.1095, -0.0994,  0.3540,  0.0662, -0.0710,  0.0451,
         -0.0096,  0.0713, -0.0259, -0.1008,  0.2891,  0.3169,  0.2417,  0.3659,
          0.1421,  0.2349,  0.3089,  0.2376,  0.0127,  0.0286]],
       requires_grad=True)

In [29]:
model.linear.bias

Parameter containing:
tensor([-0.3233], requires_grad=True)

In [31]:
# model evaluation
model.eval() #set the model to evaluate mode
accuracy_list = []

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    # forward pass
    y_pred = model(batch_features.float())
    y_pred = (y_pred > 0.8).float() #convert probabilites to binary predictions
    # calculate accuracy for current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)


# calculate the overall accuracy
accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {accuracy}')

Accuracy: 0.96875